[versions]
minestom = "1_21_4-bb14804d42"
tinylog = "2.7.0"
junit = "5.10.0"
mockito = "5.16.0"

[libraries]
minestom = { group = "net.minestom", name = "minestom-snapshots", version.ref = "minestom" }
tinylog-api = { group = "org.tinylog", name = "tinylog-api", version.ref = "tinylog" }
tinylog-impl = { group = "org.tinylog", name = "tinylog-impl", version.ref = "tinylog" }
tinylog-slf4j = { group = "org.tinylog", name = "slf4j-tinylog", version.ref = "tinylog" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
